spring.application.name=HelloWorld

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/tododb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=root

# JPA / Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Fixed typo (formatted_sql) and value (true)
spring.jpa.properties.hibernate.format_sql=true

//spring.security.user.name=admin
//spring.security.user.password=root